### ISSUE TITLE
Can I use it? because it is not working now..

### ISSUE THREAD

**Issue by jujbob** [clab/language-universal-parser#2]
I am not sure it is available or not now because there are some errors to make a clone for "cnn" and also it is impossible to get the codes as a public user.

Thanks!

**Comment by jujbob** [comment]
It looks working

The reason why it was not working is that the submodule of "cnn" have changed to "dynet"
So I tried to download old-version of "cnn" which can download in this link (https://github.com/clab/dynet/tree/6b4b841a481a459a10633e92ff0abe760ba79403)

So if you want to use this code. Do not follow the first part of guide (installing "cnn" by git submodule)
Just install "cnn" by in the link. and then try again.

**Comment by wammar** [comment]
Sorry for not responding to this sooner! Somehow, I didn't receive an email notification. 

Graham Neubig has kindly contributed a fix for this. Please let me know if this is still a problem.

**Comment by jujbob** [comment]
It has been solved by changing cnn to dynet. Thanks for Ammar and Graham Neubig :)
